version: 0.2

phases:
  build:
    commands:
      - "pip3 install checkov"
      - "terraform init -input=false -no-color" 
      - "terraform plan -out tf.plan"
      - "terraform show -json tf.plan  > tf.json"
      - "checkov --file tf.json"